version: "3.9"
services:
  admin:
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    image: adminer:4.8.1-standalone

  database:
    volumes:
      - database-storage:/pgdata
    restart: always
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: admin
      POSTGRES_DB: OrderHub
    ports:
      - 5432:5432
    secrets:
      - db_password
volumes:
  database-storage:
secrets:
  db_password:
    file: ./secrets/db_password.txt
